BoilerBuzz/Main Views/DrinksDetailView.swift, BoilerBuzz/Main Views/Login/ForgotPasswordView.swift, BoilerBuzz/Main Views/Login/LoginView.swift, BoilerBuzz/Main Views/Login/SignUpView.swift, BoilerBuzz/Main Views/Login/VerificationView.swift, BoilerBuzz/Main Views/SpendingView.swift, BoilerBuzz/Server/Models/User.js, BoilerBuzz/Server/Routes/auth.js, BoilerBuzz/Server/Routes/drinks.js, BoilerBuzz/Server/server.js
A user can click a check mark to check off a drink. The change is saved in the database and is loaded when the drinks page is loaded
The data for which drinks a user has tried is stored in their user profile as an array of "triedDrinks".
UPDATE: Did frontend for the spending page and also modified the login/signup frontend
=> Full Stack For Checking off Drinks

BoilerBuzz.xcodeproj/project.pbxproj, BoilerBuzz/Main Views/AccountPage/Settings/PrivacySecuritySettingsView.swift, BoilerBuzz/Server/Routes/auth.js, BoilerBuzz/info.plist
added an update password feature which can be found on the settings page>privacy and security and it asks for your old password and asks for a new one
=> Implement password change feature and update related files

BoilerBuzz/Main Views/SpendingView.swift, BoilerBuzz/Server/Models/User.js, BoilerBuzz/Server/Routes/spending.js, BoilerBuzz/Server/server.js
Added Backend and database connection to the spending page. Everything is completed except for the monthly reset on spending. 
Accounted for dark mode also
=> full stack spending page

BoilerBuzz/Main Views/DrinksDetailView.swift
added filter for drink page view
=> Filter branch

BoilerBuzz/Main Views/DrinksDetailView.swift
This was just Matthews latest changes
=> Merged main to Patrick then to dev

BoilerBuzz/Main Views/DrinksDetailView.swift
added to the filter to include filtering by bar not just drink type
=> Added filtering by bar

BoilerBuzz/Main Views/DrinksDetailView.swift, BoilerBuzz/Server/Models/User.js
added a couple lines for the shake for random drink
=> random drink fix

BoilerBuzz/Server/server.js
created a cron job in the server to reset the spending and expenses on the first of each month at midnight
=> monthly reset for spending

BoilerBuzz/Main Views/DrinksDetailView.swift, BoilerBuzz/Server/server.js
Added a sorting feature to the drinks page
=> sort drinks

BoilerBuzz.xcodeproj/project.pbxproj, BoilerBuzz/Main Views/AccountPage/Settings/PrivacySecuritySettingsView.swift, BoilerBuzz/Main Views/DrinksDetailView.swift, BoilerBuzzTests/DrinksDetailViewTests.swift, BoilerBuzzTests/GoogleMapViewRepresentableTests.swift, BoilerBuzzTests/PrivacySecuritySettingsViewTests.swift
Has the bar filter and testing for all my user stories
=> Barfilterfinal

BoilerBuzz/BoilerBuzzApp.swift, BoilerBuzz/ContentView.swift, BoilerBuzz/Main Views/AccountPage/AccountView.swift, BoilerBuzz/Main Views/AccountPage/ProfileViewModel.swift, BoilerBuzz/Main Views/AccountPage/Settings/AccountSettingsView.swift, BoilerBuzz/Main Views/AccountPage/Settings/SettingsView.swift, BoilerBuzzTests/ProfileSettingsTests.swift, BoilerBuzzUITests/ProfileSettingsUITests.swift, Server/Routes/friends.js, Server/Routes/profile.js, Server/test/banUser.test.mjs, Server/test/favoritedrinks.test.mjs, Server/test/friends.test.mjs, Server/test/profile.test.mjs
Bug fixed a few things that were brought up. The auto capitalize in the username, going to a friends page now always shows a checkmark if friends, doesnt if you remove them as a friend. Banning users now works, it just sets the isBanned in the database to true.
Tests for Settings page, changing username/bio, banning/unbanning, favorite drinks, friends
=> bug fixes and tests

BoilerBuzz/info.plist
=> fixed plsit

BoilerBuzz/BoilerBuzzApp.swift, BoilerBuzz/ContentView.swift, BoilerBuzz/Main Views/HomeView.swift, BoilerBuzz/info.plist
fixed the post sharing commit so that it does not affect the map.
=> Fixed the Post Sharing

Server/Routes/home.js
=> AccountView can now see events made by that account

BoilerBuzz/Main Views/HomeView.swift, Server/Routes/home.js
Can see profile pic and username in event details and can click it to go to their account
=> Profile view in event details

BoilerBuzz/Main Views/AccountPage/AccountView.swift, BoilerBuzz/Main Views/AccountPage/FriendsListPopup.swift, BoilerBuzz/Main Views/AccountPage/Settings/NotificationsSettingsView.swift, Server/test/eventDelete.test.mjs, Server/test/eventReport.test.mjs, Server/test/notificationPreferences.test.mjs, Server/test/rating.test.mjs
Changed where it said Posts and New Post in Account Page to Events and New Event
=> UI change and tests

BoilerBuzz/Main Views/HomeView.swift
fixed it so now it doesn't add 1 hour. I thought the time was calculated wrong but it was because my vm is on central time... idiot
=> fixed time zone diff

BoilerBuzz/Main Views/AccountPage/Notifications/NotificationManager.swift, BoilerBuzz/Main Views/AccountPage/ProfileViewModel.swift, BoilerBuzz/Main Views/HomeView.swift, BoilerBuzz/SocketIOManager.swift, Server/Routes/location.js, Server/eventWatcher.js
We now have notifications for
Friends (that you have preferences on for) creating an event
Updating and deleting events that you are rsvp'd to.
And scheduled reminders that send notification 30 minutes before an event starts that you are rsvp'd to. And wont if you rsvp but then unrsvp
These dont send notifications if you do not have them checked on in the settings.
=> More notifications

BoilerBuzz/Main Views/HomeView.swift, BoilerBuzz/info.plist
when you click on the location on the events page, it will open in google maps if you have the app. Otherwise it will open in a web browser
=> open in actual maps

BoilerBuzz/LocationManager.swift
Changed to update user location every 15 seconds instead of 1 second to reduce network traffic
=> updated location tracking

BoilerBuzz/Main Views/CalendarView.swift
=> Calendar week and month view
